name: Bug report
description: Report a reproducible defect in EvidenceOS
labels:
  - bug
body:
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Tag or commit SHA where the bug was observed
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Exact commands, inputs, and expected result
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: tests
    attributes:
      label: Test additions or gaps
      description: Describe what test should be added or updated to prevent regressions.
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Confirmation
      options:
        - label: I provided reproducible steps.
          required: true
        - label: I identified a test addition/update needed for this bug.
          required: true
