name: Feature request
description: Propose an improvement for EvidenceOS
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What limitation are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed behavior
      description: Include user impact and API/protocol implications.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps for current limitation
      description: Steps or scenario that demonstrate the current gap.
    validations:
      required: true

  - type: textarea
    id: tests
    attributes:
      label: Test additions
      description: Describe new tests needed (or why no tests are needed).
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Confirmation
      options:
        - label: I provided reproducible scenario steps.
          required: true
        - label: I described required test additions.
          required: true
